### PR TITLE
use picker from "@react-native-picker/picker" package

### PR DESCRIPTION
**Pull request by imbudhiraja**
**Descrition**
1. use picker from "@react-native-picker/picker" package

### CODE REVIEW

**Comment by sidongmen** [comment]
This works fine.

**Review by jbourgault — APPROVED** [review]

**Comment by hexadecy** [comment]
Similar PR already merged in master: https://github.com/kalontech/ReactNativeWheelPicker/pull/136

**Comment by dibat** [comment]
> Similar PR already merged in master: #136, please close.

@hexadecy, @react-native-community/picker package has been deprecated and replaced with @react-native-picker/picker
See https://www.npmjs.com/package/@react-native-community/picker
```
This package has been deprecated
Author message:

this library has been renamed to @react-native-picker/picker. See the GitHub new repository: https://github.com/react-native-picker/picker
```

**Comment by SaadBinWaheed-empglabs** [comment]
Shouldn't this PR be merged?

I am getting the error:

> Invariant Violation: Picker has been removed from React Native. It can now be installed and imported from '@react-native-picker/picker' instead of 'react-native'. See https://github.com/react-native-picker/picker

**Pull request closed without merging**
